### ISSUE TITLE
Colab Notebook not Working

### ISSUE THREAD

**Issue by FabioSeixal** [gokhantuffer/vapoursynth-google-colab-installation#1]
Hello,

When trying to build VapourSynth via current Notebook, we get multiple errors.
Can You have a look?

I have a very old PC and Colab is my only way of doing good video enconding.
I'm also not the best Python programmer in this world.

Many Thanks in advance for the help

**Comment by gokhantuffer** [comment]
Updated. Check it out.

**Comment by gokhantuffer** [comment]
Hi. Updated it. You can check it.

**Comment by FabioSeixal** [comment]
Thank You!!!
For me it was still necessary to ran "!sudo ldconfig" in the end as I was not able to import Vapoursynth CORE

Thanks a lot honestly!
